### ISSUE TITLE
panic  when creating a new hpa

### ISSUE THREAD

**Issue by winjer** [kedacore/keda#1271]
This is with v2.0.0-rc, I am getting:

```
E1019 11:36:26.826680       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 246 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1e298a0, 0x32944e0)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/runtime/runtime.go:48 +0x89
panic(0x1e298a0, 0x32944e0)
        /usr/local/go/src/runtime/panic.go:969 +0x175
go.opencensus.io/trace.FromContext(...)
        /go/pkg/mod/go.opencensus.io@v0.22.4/trace/trace.go:113
go.opencensus.io/trace.StartSpan(0x0, 0x0, 0x210dd05, 0xc, 0x0, 0x0, 0x0, 0x203000, 0x203000, 0x203000)
        /go/pkg/mod/go.opencensus.io@v0.22.4/trace/trace.go:172 +0x70
github.com/Azure/azure-event-hubs-go.(*Hub).startSpanFromContext(0xc00012b860, 0x0, 0x0, 0x210dd05, 0xc, 0x0, 0x0, 0x0, 0x30, 0xc0009cfbc0, ...)
        /go/pkg/mod/github.com/!azure/azure-event-hubs-go@v1.3.1/tracing.go:13 +0x7a
github.com/Azure/azure-event-hubs-go.(*Hub).Close(0xc00012b860, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/!azure/azure-event-hubs-go@v1.3.1/hub.go:538 +0x98
github.com/kedacore/keda/pkg/scalers.(*azureEventHubScaler).Close(0xc000901b30, 0xc0009cfbc0, 0x1)
        /workspace/pkg/scalers/azure_eventhub_scaler.go:274 +0x52
github.com/kedacore/keda/controllers.(*ScaledObjectReconciler).getScaledObjectMetricSpecs(0xc0006ea700, 0x24dcf00, 0xc000aa9a40, 0xc00072efc0, 0x2, 0x0, 0x0, 0xc0009e3c80, 0x12)
        /workspace/controllers/hpa.go:162 +0x353
github.com/kedacore/keda/controllers.(*ScaledObjectReconciler).newHPAForScaledObject(0xc0006ea700, 0x24dcf00, 0xc000aa9a40, 0xc00072efc0, 0xc00054fb50, 0x4, 0x21, 0x0)
        /workspace/controllers/hpa.go:44 +0x6a
github.com/kedacore/keda/controllers.(*ScaledObjectReconciler).createAndDeployNewHPA(0xc0006ea700, 0x24dcf00, 0xc000aa9a40, 0xc00072efc0, 0xc000b5fb50, 0xc000aa3950, 0x21)
        /workspace/controllers/hpa.go:27 +0x225
github.com/kedacore/keda/controllers.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists(0xc0006ea700, 0x24dcf00, 0xc000aa9a40, 0xc00072efc0, 0xc000b5fb50, 0x4, 0x2100a9b, 0x2)
        /workspace/controllers/scaledobject_controller.go:279 +0x35e
github.com/kedacore/keda/controllers.(*ScaledObjectReconciler).reconcileScaledObject(0xc0006ea700, 0x24dcf00, 0xc000aa9a40, 0xc00072efc0, 0x0, 0x0, 0x18, 0x24969a0)
        /workspace/controllers/scaledobject_controller.go:179 +0x151
github.com/kedacore/keda/controllers.(*ScaledObjectReconciler).Reconcile(0xc0006ea700, 0xc0007ce960, 0x9, 0xc0007a59e0, 0x18, 0xc000aa99e0, 0xc000630870, 0xc000630368, 0xc000630360)
        /workspace/controllers/scaledobject_controller.go:143 +0x405
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00073c750, 0x1ebfc20, 0xc000aa9360, 0xc00051ef00)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235 +0x2a9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00073c750, 0x203000)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209 +0xb0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00073c750)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000aa6f70)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000aa6f70, 0x2488b60, 0xc000aabb30, 0x1, 0xc00019b6e0)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000aa6f70, 0x3b9aca00, 0x0, 0x21e8501, 0xc00019b6e0)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000aa6f70, 0x3b9aca00, 0xc00019b6e0)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:170 +0x3fa
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x171ce30]

goroutine 246 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x1e298a0, 0x32944e0)
        /usr/local/go/src/runtime/panic.go:969 +0x175
go.opencensus.io/trace.FromContext(...)
        /go/pkg/mod/go.opencensus.io@v0.22.4/trace/trace.go:113
go.opencensus.io/trace.StartSpan(0x0, 0x0, 0x210dd05, 0xc, 0x0, 0x0, 0x0, 0x203000, 0x203000, 0x203000)
        /go/pkg/mod/go.opencensus.io@v0.22.4/trace/trace.go:172 +0x70
github.com/Azure/azure-event-hubs-go.(*Hub).startSpanFromContext(0xc00012b860, 0x0, 0x0, 0x210dd05, 0xc, 0x0, 0x0, 0x0, 0x30, 0xc0009cfbc0, ...)
        /go/pkg/mod/github.com/!azure/azure-event-hubs-go@v1.3.1/tracing.go:13 +0x7a
github.com/Azure/azure-event-hubs-go.(*Hub).Close(0xc00012b860, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/!azure/azure-event-hubs-go@v1.3.1/hub.go:538 +0x98
github.com/kedacore/keda/pkg/scalers.(*azureEventHubScaler).Close(0xc000901b30, 0xc0009cfbc0, 0x1)
        /workspace/pkg/scalers/azure_eventhub_scaler.go:274 +0x52
github.com/kedacore/keda/controllers.(*ScaledObjectReconciler).getScaledObjectMetricSpecs(0xc0006ea700, 0x24dcf00, 0xc000aa9a40, 0xc00072efc0, 0x2, 0x0, 0x0, 0xc0009e3c80, 0x12)
        /workspace/controllers/hpa.go:162 +0x353
github.com/kedacore/keda/controllers.(*ScaledObjectReconciler).newHPAForScaledObject(0xc0006ea700, 0x24dcf00, 0xc000aa9a40, 0xc00072efc0, 0xc00054fb50, 0x4, 0x21, 0x0)
        /workspace/controllers/hpa.go:44 +0x6a
github.com/kedacore/keda/controllers.(*ScaledObjectReconciler).createAndDeployNewHPA(0xc0006ea700, 0x24dcf00, 0xc000aa9a40, 0xc00072efc0, 0xc000b5fb50, 0xc000aa3950, 0x21)
        /workspace/controllers/hpa.go:27 +0x225
github.com/kedacore/keda/controllers.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists(0xc0006ea700, 0x24dcf00, 0xc000aa9a40, 0xc00072efc0, 0xc000b5fb50, 0x4, 0x2100a9b, 0x2)
        /workspace/controllers/scaledobject_controller.go:279 +0x35e
github.com/kedacore/keda/controllers.(*ScaledObjectReconciler).reconcileScaledObject(0xc0006ea700, 0x24dcf00, 0xc000aa9a40, 0xc00072efc0, 0x0, 0x0, 0x18, 0x24969a0)
        /workspace/controllers/scaledobject_controller.go:179 +0x151
github.com/kedacore/keda/controllers.(*ScaledObjectReconciler).Reconcile(0xc0006ea700, 0xc0007ce960, 0x9, 0xc0007a59e0, 0x18, 0xc000aa99e0, 0xc000630870, 0xc000630368, 0xc000630360)
        /workspace/controllers/scaledobject_controller.go:143 +0x405
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00073c750, 0x1ebfc20, 0xc000aa9360, 0xc00051ef00)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235 +0x2a9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00073c750, 0x203000)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209 +0xb0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00073c750)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000aa6f70)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000aa6f70, 0x2488b60, 0xc000aabb30, 0x1, 0xc00019b6e0)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000aa6f70, 0x3b9aca00, 0x0, 0x21e8501, 0xc00019b6e0)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000aa6f70, 0x3b9aca00, 0xc00019b6e0)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:170 +0x3fa
```

scaledobject:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  annotations:
    meta.helm.sh/release-name: trading-platform
    meta.helm.sh/release-namespace: doug-test
  creationTimestamp: "2020-10-19T11:17:13Z"
  finalizers:
  - finalizer.keda.sh
  generation: 6
  labels:
    app.kubernetes.io/instance: trading-platform
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hub-sql-processor
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: electron-trading-engine-0.1.0
    scaledObjectName: hub-sql-processor-scaler
  name: hub-sql-processor-scaler
  namespace: doug-test
  resourceVersion: "8268463"
  selfLink: /apis/keda.sh/v1alpha1/namespaces/doug-test/scaledobjects/hub-sql-processor-scaler
  uid: 05b6b8ea-d3a9-42a6-ba29-dd5a7940f82e
spec:
  scaleTargetRef:
    name: hub-sql-processor
  triggers:
  - metadata:
      connectionFromEnv: ConnectionStrings__EventHubConnection
      storageConnectionFromEnv: ConnectionStrings__AzureWebJobsStorage
    type: azure-eventhub
```

**Comment by eashi** [comment]
I was going through this and then saw that this is fixed by commit https://github.com/kedacore/keda/commit/071d5a0732c547cf58199fab0772fcee5c9efc85#diff-6fc473c7ab48fd3313eaa7e64d19a2dfbff74ff111a4d86e11d12f582b0f83f0

**Comment by zroubalik** [comment]
@eashi thanks for the confirmation!
