### ISSUE TITLE
Unable to upgrade nor delete a scaledobject

### ISSUE THREAD

**Issue by sebastienle14** [kedacore/keda#2507]
### Discussed in https://github.com/kedacore/keda/discussions/2500

<div type='discussions-op-text'>

<sup>Originally posted by **sebastienle14** January 21, 2022</sup>
Greetings,

My Kubernetes env is stucked on the following issue, meaning the issue won't go away even after a clean restart of the entire cluster.

Yes, it has been caused by removing a deployment BEFORE removing the KEDA ScalingRules. Yes, it was a mistake, The procedure on how to handle deployments with KEDA Triggers implied has now been updated. 

My main issue now is to get the cluster and this deployment back on its feet. 
I followed these 2 feedbacks: 
https://github.com/kedacore/keda/discussions/2159
https://github.com/kedacore/keda/issues/1470

... but it didn't helped me much on how to cleanup the mess we made. I'm running a microk8s cluster here. 

```

I0121 13:36:10.704445       1 request.go:665] Waited for 1.021691153s due to client-side throttling, not priority and fairness, request: GET:https://10.152.183.1:443/apis/flowcontrol.apiserver.k8s.io/v1beta1?timeout=32s
2022-01-21T13:36:10.808Z	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": ":8080"}
2022-01-21T13:36:10.809Z	INFO	setup	Running on Kubernetes 1.20+	{"version": "v1.20.13-35+d877e7a8ac536e"}
2022-01-21T13:36:10.810Z	INFO	setup	Starting manager
2022-01-21T13:36:10.810Z	INFO	setup	KEDA Version: 2.5.0
2022-01-21T13:36:10.810Z	INFO	setup	Git Commit: 22d71631c7a6e0e0ea8aef434263321d65975c29
2022-01-21T13:36:10.810Z	INFO	setup	Go Version: go1.17.3
2022-01-21T13:36:10.810Z	INFO	setup	Go OS/Arch: linux/amd64
I0121 13:36:10.810742       1 leaderelection.go:248] attempting to acquire leader lease keda/operator.keda.sh...
2022-01-21T13:36:10.810Z	INFO	Starting metrics server	{"path": "/metrics"}
I0121 13:36:26.521378       1 leaderelection.go:258] successfully acquired lease keda/operator.keda.sh
2022-01-21T13:36:26.521Z	INFO	controller.clustertriggerauthentication	Starting EventSource	{"reconciler group": "keda.sh", "reconciler kind": "ClusterTriggerAuthentication", "source": "kind source: *v1alpha1.ClusterTriggerAuthentication"}
2022-01-21T13:36:26.521Z	INFO	controller.scaledjob	Starting EventSource	{"reconciler group": "keda.sh", "reconciler kind": "ScaledJob", "source": "kind source: *v1alpha1.ScaledJob"}
2022-01-21T13:36:26.521Z	INFO	controller.clustertriggerauthentication	Starting Controller	{"reconciler group": "keda.sh", "reconciler kind": "ClusterTriggerAuthentication"}
2022-01-21T13:36:26.521Z	INFO	controller.scaledjob	Starting Controller	{"reconciler group": "keda.sh", "reconciler kind": "ScaledJob"}
2022-01-21T13:36:26.522Z	INFO	controller.scaledobject	Starting EventSource	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "source": "kind source: *v1alpha1.ScaledObject"}
2022-01-21T13:36:26.522Z	INFO	controller.scaledobject	Starting EventSource	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "source": "kind source: *v2beta2.HorizontalPodAutoscaler"}
2022-01-21T13:36:26.522Z	INFO	controller.triggerauthentication	Starting EventSource	{"reconciler group": "keda.sh", "reconciler kind": "TriggerAuthentication", "source": "kind source: *v1alpha1.TriggerAuthentication"}
2022-01-21T13:36:26.522Z	INFO	controller.scaledobject	Starting Controller	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject"}
2022-01-21T13:36:26.522Z	INFO	controller.triggerauthentication	Starting Controller	{"reconciler group": "keda.sh", "reconciler kind": "TriggerAuthentication"}
2022-01-21T13:36:26.622Z	INFO	controller.clustertriggerauthentication	Starting workers	{"reconciler group": "keda.sh", "reconciler kind": "ClusterTriggerAuthentication", "worker count": 1}
2022-01-21T13:36:26.623Z	INFO	controller.scaledjob	Starting workers	{"reconciler group": "keda.sh", "reconciler kind": "ScaledJob", "worker count": 1}
2022-01-21T13:36:26.623Z	INFO	controller.triggerauthentication	Starting workers	{"reconciler group": "keda.sh", "reconciler kind": "TriggerAuthentication", "worker count": 1}
2022-01-21T13:36:26.623Z	INFO	controller.scaledobject	Starting workers	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "worker count": 5}
2022-01-21T13:36:26.623Z	INFO	controller.scaledobject	Reconciling ScaledObject	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "batch-myscalinapp-z", "namespace": "z-myscalinapp"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x235bea1]
goroutine 244 [running]:
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).finalizeScaledObject(0xc000d43200, {0x2fd9df8, 0xc000ce2450}, {0x2ffde50, 0xc0004ed470}, 0xc000176a00)
/workspace/controllers/keda/scaledobject_finalizer.go:48 +0x141
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile(0xc000d43200, {0x2fd9df8, 0xc000ce2450}, {{{0xc000ff8990, 0x27f99a0}, {0xc000ff8980, 0xc000cb3300}}})
/workspace/controllers/keda/scaledobject_controller.go:162 +0x7e6
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0003130e0, {0x2fd9df8, 0xc000ce23c0}, {{{0xc000ff8990, 0x27f99a0}, {0xc000ff8980, 0xc00102a2c0}}})
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:114 +0x222
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0003130e0, {0x2fd9d50, 0xc000c87e80}, {0x2708660, 0xc000459dc0})
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:311 +0x2f2
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0003130e0, {0x2fd9d50, 0xc000c87e80})
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:223 +0x356
```

Here is my KEDA trigger config for myscalinapp:

```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: batch-ot-queue-auth
spec:
  podIdentity:
    provider: none
  secretTargetRef:
  - parameter: connection
    name: batch-ot-queue-cs-secret
    key: azure-storage-connectionstring
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: batch-myscalinapp-z
  namespace: z-myscalinapp
spec:
  scaleTargetRef:
    name: z-myscalinapp-app
    #envSourceContainerName: otextensionsolver-container #Optional. Default: deployment.spec.template.spec.containers[0]
  pollingInterval: 2                                 # Optional. Default: 30 seconds
  cooldownPeriod:  300                               # Optional. Default: 300 seconds
  minReplicaCount: 2                                 # Optional. Default: 0
  maxReplicaCount: 4                                 # Optional. Default: 100
  advanced:                                          # Optional. Section to specify advanced options
    restoreToOriginalReplicaCount: true              # Optional. Default: false
  triggers:
  - type: azure-queue
    metadata:
      queueName: batch-myscalinapp-otsf
      queueLength: '1'
      accountName: zgcbatchstor001
    authenticationRef:
      name: batch-ot-queue-auth
  - type: azure-queue
    metadata:
      queueName: batch-myscalinapp-ts
      queueLength: '1'
      accountName: zgcbatchstor001
    authenticationRef:
      name: batch-ot-queue-auth
  - type: azure-queue
    metadata:
      queueName: batch-myscalinapp-proto
      queueLength: '1'
      accountName: zgcbatchstor001
    authenticationRef:
      name: batch-ot-queue-auth
```

When trying to reapply the scalingRules, and after the myscalinapp deployment is completed, here is what I get: 

```
PS C:\dev> kubectl apply --namespace z-myscalinapp -f ./myscalinapp/scalingRules/myscalinapp-scalingrules.yaml
Warning: Detected changes to resource batch-myscalinapp-z which is currently being deleted.
```

The message is the same when trying to delete. The command remains stucked. The behavior is the same when trying to delete the  z-myscalinapp namespace

How could I set thing straight again, without having to recreate the entire cluster?

Best Regards, 
</div>

**Comment by zroubalik** [comment]
Hi, plase try to remove finalizers from the ScaledObject that you are trying to delete.

**Comment by sebastienle14** [comment]
greetings @zroubalik 

Sadly, trying to remove the finalizers doesn't do much: 
`$ kubectl get namespace z-myscalinapp -o=json | jq '.spec.finalizers = null' | kubectl apply -f -`

even tried : 
`$ kubectl get namespace z-myscalinapp -o=json | jq '.metadata.finalizers = null' | kubectl apply -f -`

and when I check the namespace again, finalizers is still defined: 
```
(...)
        "name": "z-myscalinapp",
        "resourceVersion": "17833213",
        "selfLink": "/api/v1/namespaces/z-myscalinapp",
        "uid": "d65b0b1a-6b40-4e3e-909f-518764d1762b"
    },
    "spec": {
        "finalizers": [
            "kubernetes"
        ]
    },
    "status": {
        "phase": "Active"
    }
(...)
```

**Comment by zroubalik** [comment]
Try to remove finalizers from ScaledObjects in the namespace

**Comment by sebastienle14** [comment]
Thank you, I managed to get further thanks to your advice:
```
~$ kubectl get ScaledObjects batch-myscalinapp-z -n z-myscalinapp -o=json | jq '.metadata.finalizers = null' | kubectl apply -f -
Warning: Detected changes to resource batch-myscalinapp-z which is currently being deleted.
scaledobject.keda.sh/batch-myscalinapp-z configured
```

After this, the object disppeared:
```
~$ kubectl get ScaledObjects batch-myscalinapp-z -n z-myscalinapp -o=json
Error from server (NotFound): the server could not find the requested resource (get scaledobjects.keda.sh batch-myscalinapp-z
```

And I was able to clean install everything again! Thank you very much!

**Comment by wmgroot** [comment]
Removing finalizers to clean up a ScaledObject with no selected Deployment is not an acceptable workaround. Why does the finalizer prevent deletion of the ScaledObject when the Deployment has already been deleted?

This behavior will cause race conditions with cases such as namespace deletion and non-deterministic deletion order of resources in the namespace.

**Comment by s6-marct** [comment]
We also had an already-deleted Deployment referenced in our ScaledObject, which makes it impossible (without the below steps) to remove the finalizer.

What worked today for us:
- Temporarily delete the `ValidatingWebhookConfiguration` webhook (`keda-admission`)
- `null` out the finalizer on the ScaledObject
- restore the webhook
