### ISSUE TITLE
Keda panics when I am trying to get a metric that doesn't exist

### ISSUE THREAD

**Issue by edganiukov** [kedacore/keda#324]
After trying  to execute `kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/default/asdasd"` I got 500 error, instead of 400, because this metrics dosn't exist.
```
I0826 13:16:53.859170       1 handler.go:143] custom-metrics-adapter: GET "/apis/external.metrics.k8s.io/v1beta1/namespaces/default/asdasd" satisfied by gorestful with webservice /apis/external.metrics.k8s.io/v1beta1
I0826 13:16:53.861839       1 request.go:942] Response Body: {"apiVersion":"keda.k8s.io/v1alpha1","items":[],"kind":"ScaledObjectList","metadata":{"continue":"","resourceVersion":"46674306","selfLink":"/apis/keda.k8s.io/v1alpha1/namespaces/default/scaledobjects"}}
time="2019-08-26T13:16:53Z" level=error msg="Cannot get metrics for Namespace default MetricSelector  and Metrics asdasd. Error: Exactly one scaled object should match label "
E0826 13:16:53.861984       1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"Exactly one scaled object should match label "}
I0826 13:16:53.862219       1 wrap.go:47] GET /apis/external.metrics.k8s.io/v1beta1/namespaces/default/asdasd: (3.703502ms) 500
goroutine 764 [running]:
github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc0001542a0, 0x1f4)
        /go/src/github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:204 +0xc8
github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc0001542a0, 0x1f4)
        /go/src/github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:183 +0x35
github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc0001d29a0, 0x1f4)
        /go/src/github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:205 +0xa6
github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/endpoints/metrics.(*ResponseWriterDelegator).WriteHeader(0xc000444fc0, 0x1f4)
        /go/src/github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:307 +0x45
github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.httpResponseWriterWithInit.Write(0x0, 0x1ebf0ce, 0x10, 0x1f4, 0x22c5340, 0xc000776050, 0xc000a1c140, 0x8a, 0x129, 0xc0007cc0e8, ...)
        /go/src/github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:51 +0x1ba
encoding/json.(*Encoder).Encode(0xc0007cc1e8, 0x1e0abe0, 0xc0006e6870, 0x0, 0x0)
        /usr/local/go/src/encoding/json/stream.go:225 +0x1cb
github.com/kedacore/keda/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc000584000, 0x22a6e80, 0xc0006e6870, 0x2286040, 0xc0004aae40, 0x19caac4, 0x6)
        /go/src/github.com/kedacore/keda/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:246 +0x2e4
github.com/kedacore/keda/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0xc0006e6900, 0x22a6e80, 0xc0006e6870, 0x2286040, 0xc0004aae40, 0xc000584000, 0x2283a60)
        /go/src/github.com/kedacore/keda/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:201 +0x297
github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x1ebf0ce, 0x10, 0x7f56e5527bc0, 0xc0006e6900, 0x22c5340, 0xc000776050, 0xc0002cdc00, 0x1f4, 0x22a6e80, 0xc0006e6870)
        /go/src/github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:116 +0x11b
github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x22c7b00, 0xc0004c7260, 0x1ed07c7, 0x17, 0x1ea2aa0, 0x7, 0x22c5340, 0xc000776050, 0xc0002cdc00, 0x1f4, ...)
        /go/src/github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:142 +0x3d7
github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.ErrorNegotiated(0x2281120, 0xc0000b4a00, 0x22c7b00, 0xc0004c7260, 0x1ed07c7, 0x17, 0x1ea2aa0, 0x7, 0x22c5340, 0xc000776050, ...)
        /go/src/github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:161 +0x149
github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/endpoints/handlers.(*RequestScope).err(...)
        /go/src/github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:72
github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/endpoints/handlers.ListResource.func1(0x22c5340, 0xc000776050, 0xc0002cdc00)
        /go/src/github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/endpoints/handlers/get.go:264 +0x14f4
github.com/kedacore/keda/vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/installer.restfulListResource.func1(0xc000444cc0, 0xc000154380)
        /go/src/github.com/kedacore/keda/vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/installer/installer.go:286 +0xe5
github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc000444cc0, 0xc000154380)
        /go/src/github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:225 +0x200
github.com/kedacore/keda/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc000492510, 0x7f56e548e048, 0xc000776030, 0xc0002cdc00)
        /go/src/github.com/kedacore/keda/vendor/github.com/emicklei/go-restful/container.go:288 +0xa3b
github.com/kedacore/keda/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(...)
        /go/src/github.com/kedacore/keda/vendor/github.com/emicklei/go-restful/container.go:199
github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x1ece4eb, 0x16, 0xc000492510, 0xc00004d6c0, 0x7f56e548e048, 0xc000776030, 0xc0002cdc00)
        /go/src/github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/server/handler.go:146 +0x4e4
github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7f56e548e048, 0xc000776030, 0xc0002cdc00)
        /go/src/github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64 +0x4eb
net/http.HandlerFunc.ServeHTTP(0xc0008ee400, 0x7f56e548e048, 0xc000776030, 0xc0002cdc00)
        /usr/local/go/src/net/http/server.go:1995 +0x44
github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7f56e548e048, 0xc000776030, 0xc0002cdc00)
        /go/src/github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:160 +0x4a7
net/http.HandlerFunc.ServeHTTP(0xc0007b52c0, 0x7f56e548e048, 0xc000776030, 0xc0002cdc00)
        /usr/local/go/src/net/http/server.go:1995 +0x44
github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7f56e548e048, 0xc000776030, 0xc0002cdc00)
        /go/src/github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50 +0x1eb1
net/http.HandlerFunc.ServeHTTP(0xc0008ee440, 0x7f56e548e048, 0xc000776030, 0xc0002cdc00)
        /usr/local/go/src/net/http/server.go:1995 +0x44
github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7f56e548e048, 0xc000776030, 0xc0002cdb00)
        /go/src/github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:75 +0x3bf
net/http.HandlerFunc.ServeHTTP(0xc0008ee480, 0x7f56e548e048, 0xc000776030, 0xc0002cdb00)
        /usr/local/go/src/net/http/server.go:1995 +0x44
github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc000766420, 0xc00080d620, 0x22d4ac0, 0xc000776030, 0xc0002cdb00)
        /go/src/github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108 +0xb3
created by github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
        /go/src/github.com/kedacore/keda/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:97 +0x1b1
logging error output: "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Exactly one scaled object should match label \",\"code\":500}\n"

**Comment by zroubalik** [comment]
KEDA Operator and Metrics Server are separated now, you shouldn't see such problem. Please reopen if you do so.
