### ISSUE TITLE
Keda-operator container restarts if the Kafka topic / partition count is not found in broker

### ISSUE THREAD

**Issue by sinanub18** [kedacore/keda#4202]
### Report

I am using Kafka Scaler with **KEDA 2.9.0**, but whenever the Kafka topic / partition count is not found on broker after certain retries the **Keda-operator** container restarts will below error 

```
{"level":"error","ts":"2023-02-05T07:07:30Z","logger":"kafka_scaler","msg":"","type":"ScaledObject","namespace":"XXXX","name":"XXX-XXX-XXX","error":"error describing topics: kafka server: Request was for a topic or partition that does not exist on this broker","stacktrace":"github.com/kedacore/keda/v2/pkg/scalers.(*kafkaScaler).getTopicPartitions\n\t/workspace/pkg/scalers/kafka_scaler.go:398\ngithub.com/kedacore/keda/v2/pkg/scalers.(*kafkaScaler).getTotalLag\n\t/workspace/pkg/scalers/kafka_scaler.go:581\ngithub.com/kedacore/keda/v2/pkg/scalers.(*kafkaScaler).GetMetricsAndActivity\n\t/workspace/pkg/scalers/kafka_scaler.go:568\ngithub.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).GetScaledObjectState\n\t/workspace/pkg/scaling/cache/scalers_cache.go:135\ngithub.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers\n\t/workspace/pkg/scaling/scale_handler.go:356\ngithub.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop\n\t/workspace/pkg/scaling/scale_handler.go:162"}

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x167dd0b]

goroutine 4047 [running]:
github.com/kedacore/keda/v2/pkg/scaling/executor.(*scaleExecutor).RequestScale(0xc001756dc0, {0x40ba2b8, 0xc013bf7ac0}, 0xc00577a600, 0x1, 0x1)
	/workspace/pkg/scaling/executor/scale_scaledobjects.go:39 +0x16b
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers(0xc001947680, {0x40ba2b8, 0xc013bf7ac0}, {0x386ec80?, 0xc00577a600?}, {0x40a7658, 0xc0144ba7e8})
	/workspace/pkg/scaling/scale_handler.go:357 +0x559
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop(0xc001947680, {0x40ba2b8, 0xc013bf7ac0}, 0xc012eb7a40, {0x386ec80, 0xc00577a600}, {0x40a7658, 0xc0144ba7e8})
	/workspace/pkg/scaling/scale_handler.go:162 +0x32a
created by github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).HandleScalableObject
	/workspace/pkg/scaling/scale_handler.go:118 +0x71d
```

**Whereas on other environments it has restarted the container with below error, but the last log was same with Kafka topic/ paritition count missing in broker**

```
panic: close of closed channel

goroutine 4080475 [running]:
github.com/Shopify/sarama.(*client).Close(0xc01baee460)
	/workspace/vendor/github.com/Shopify/sarama/client.go:267 +0x66
github.com/Shopify/sarama.(*clusterAdmin).Close(0xc00cb37640?)
	/workspace/vendor/github.com/Shopify/sarama/admin.go:188 +0x22
github.com/kedacore/keda/v2/pkg/scalers.(*kafkaScaler).Close(0xc0135e0000?, {0xc001675108?, 0x4e315f?})
	/workspace/pkg/scalers/kafka_scaler.go:504 +0x28
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).refreshScaler(0xc0143d9620, {0x40ba360, 0xc01a740300}, 0x1)
	/workspace/pkg/scaling/cache/scalers_cache.go:247 +0x26d
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).GetMetricsForScaler(0xc0143d9620, {0x40ba360, 0xc01a740300}, 0x1, {0xc00b8a5740, 0x25})
	/workspace/pkg/scaling/cache/scalers_cache.go:82 +0x11e
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScaledObjectMetrics(0xc0016806c0, {0x40ba360, 0xc01a740300}, {0xc006bd57a0, 0x18}, {0xc00567e428, 0x4}, {0xc00b8a5740, 0x25})
	/workspace/pkg/scaling/scale_handler.go:439 +0xe92
github.com/kedacore/keda/v2/pkg/metricsservice.(*GrpcServer).GetMetrics(0xc0016849c0, {0x40ba360, 0xc01a740300}, 0xc014936ba0)
	/workspace/pkg/metricsservice/server.go:45 +0xbc
github.com/kedacore/keda/v2/pkg/metricsservice/api._MetricsService_GetMetrics_Handler({0x3486c40?, 0xc0016849c0}, {0x40ba360, 0xc01a740300}, 0xc009a3f7a0, 0x0)
	/workspace/pkg/metricsservice/api/metrics_grpc.pb.go:79 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0x40c5ff0, 0xc013e24340}, 0xc0106bb7a0, 0xc001684a50, 0x602b600, 0x0)
	/workspace/vendor/google.golang.org/grpc/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0x40c5ff0, 0xc013e24340}, 0xc0106bb7a0, 0x0)
	/workspace/vendor/google.golang.org/grpc/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/workspace/vendor/google.golang.org/grpc/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/workspace/vendor/google.golang.org/grpc/server.go:963 +0x28a
```

### Expected Behavior

KEDA container should not restart and throw some meaningful exception

### Actual Behavior

KEDA containers restarts frequently on interval of 22 / 24 hrs

### Steps to Reproduce the Problem

1. Deploy KEDA 2.9.0
2. Add Kafka scaler in Scaledobject with incorrect topic name / partition count
3. The Keda-operator containers will restart after certain retries.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.9.0

### Kubernetes Version

1.25

### Platform

Google Cloud

### Scaler Details

Kafka Scaler

**Comment by zroubalik** [comment]
This has been already fixed. Please update to KEDA 2.9.3 release.
