### ISSUE TITLE
Keda-metrics-server can't reach keda-operator

### ISSUE THREAD

**Issue by avbelyaev** [kedacore/keda#5184]
### Report

I install latest KEDA v2.12 with Helm in EKS. I'm using Kafka scaler and when I produce messages to Kafka I expect a sample service to scale on consumer lag.

However it doesn't happen. And in the logs of `keda-operator-metrics-apiserver` I see this:
```
W1114 17:22:44.958467       1 logging.go:59] [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {Addr: "keda-operator.a-m.svc.cluster.local:9666", ServerName: "keda-operator.a-m.svc.cluster.local:9666", }. Err: connection error: desc = "transport: Error while dialing: dial tcp: lookup keda-operator.a-m.svc.cluster.local on 10.230.128.2:53: no such host"
I1114 17:22:48.267369       1 client.go:88] keda_metrics_adapter/provider "msg"="Waiting for establishing a gRPC connection to KEDA Metrics Server"
E1114 17:22:48.308944       1 provider.go:91] keda_metrics_adapter/provider "msg"="timeout" "error"="timeout while waiting to establish gRPC connection to KEDA Metrics Service server" "server"="keda-operator.a-m.svc.cluster.local:9666"
I1114 17:22:48.309046       1 trace.go:236] Trace[1260412825]: "List" accept:application/vnd.kubernetes.protobuf, */*,audit-id:899ce6ac-9116-46f2-a6a0-4afcebb5497d,client:172.16.172.182,protocol:HTTP/2.0,resource:s0-kafka-mytopic1,scope:namespace,url:/apis/external.metrics.k8s.io/v1beta1/namespaces/a-m/s0-kafka-mytopic1,user-agent:kube-controller-manager/v1.27.7 (linux/amd64) kubernetes/3719c84/system:serviceaccount:kube-system:horizontal-pod-autoscaler,verb:LIST (14-Nov-2023 17:21:48.252) (total time: 60056ms):
Trace[1260412825]: [1m0.056898777s] [1m0.056898777s] END
E1114 17:22:48.309267       1 timeout.go:142] post-timeout activity - time-elapsed: 63.059454ms, GET "/apis/external.metrics.k8s.io/v1beta1/namespaces/a-m/s0-kafka-mytopic1" result: runtime error: invalid memory address or nil pointer dereference
goroutine 2390 [running]:
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1()
	/workspace/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:110 +0x9c
panic({0x2834040, 0x4a21350})
	/usr/local/go/src/runtime/panic.go:884 +0x213
sigs.k8s.io/custom-metrics-apiserver/pkg/registry/external_metrics.(*REST).List(0xc000047a10, {0x31dae78, 0xc0011e5890}, 0x0?)
	/workspace/vendor/sigs.k8s.io/custom-metrics-apiserver/pkg/registry/external_metrics/reststorage.go:92 +0x120
k8s.io/apiserver/pkg/endpoints/handlers.ListResource.func1({0x31da0d0, 0xc0007d3060}, 0xc0011e3100)
	/workspace/vendor/k8s.io/apiserver/pkg/endpoints/handlers/get.go:278 +0xf3b
sigs.k8s.io/custom-metrics-apiserver/pkg/apiserver/installer.restfulListResource.func1(0xc0007d2fc0, 0xc0001dc540)
	/workspace/vendor/sigs.k8s.io/custom-metrics-apiserver/pkg/apiserver/installer/installer.go:274 +0x6b
k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc0007d2fc0, 0xc0001dc540)
	/workspace/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:571 +0x22c
github.com/emicklei/go-restful/v3.(*Container).dispatch(0xc000ef4990, {0x31da0d0, 0xc0007d2820}, 0xc0011e3100)
	/workspace/vendor/github.com/emicklei/go-restful/v3/container.go:299 +0x5db
github.com/emicklei/go-restful/v3.(*Container).Dispatch(...)
	/workspace/vendor/github.com/emicklei/go-restful/v3/container.go:204
k8s.io/apiserver/pkg/server.director.ServeHTTP({{0x2cca0cb?, 0x40bdf4?}, 0xc000ef4990?, 0xc000fe99d0?}, {0x31da0d0, 0xc0007d2820}, 0xc0011e3100)
	/workspace/vendor/k8s.io/apiserver/pkg/server/handler.go:146 +0x4e7
k8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1({0x31da0d0, 0xc0007d2820}, 0xc0011e3100)
	/workspace/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:110 +0x1ca
net/http.HandlerFunc.ServeHTTP(0x31dae78?, {0x31da0d0?, 0xc0007d2820?}, 0x4?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
k8s.io/apiserver/pkg/endpoints/filters.withAuthorization.func1({0x31da0d0, 0xc0007d2820}, 0xc0011e3100)
	/workspace/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:78 +0x654
net/http.HandlerFunc.ServeHTTP(0xc14d090b0eb805ad?, {0x31da0d0?, 0xc0007d2820?}, 0xc0004514b8?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
```

This is the last line of keda-operator logs
```
2023-11-14T17:17:50Z	INFO	grpc_server	Starting Metrics Service gRPC Server	{"address": ":9666"}
```

### Expected Behavior

- service to scale on Kafka lag

### Actual Behavior

- errors,stacktraces in metrics-server, service doesn't scale

## KEDA v2.12

  1. Install KEDA v2.12 on EKS `helm install keda kedacore/keda --namespace a-m --set metricsServer.dnsPolicy=ClusterFirst,metricsServer.useHostNetwork=true`
  2. Realise that v2.12 doesnt expose port 9666 on keda-operator pods. It's exposed in the service however:
```
$ helm install keda kedacore/keda --namespace a-m --dry-run
---
# Source: keda/templates/manager/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: keda-operator
spec:
  ports:
  - name: metricsservice
    port: 9666
    targetPort: 9666
---
# Source: keda/templates/manager/deployment.yaml
kind: Deployment
metadata:
  name: keda-operator
spec:
  template:
    spec:
      containers:
        - name: keda-operator
          ...
          ports:                                       <--- only 8080 here
          - containerPort: 8080
            name: http
            protocol: TCP
          env:
            - name: WATCH_NAMESPACE
              value: ""
```
3. Edit deployment to expose 9666
4. Connection issues still persist

## KEDA from master
1. Install KEDA from master:
```
$ git clone https://github.com/kedacore/charts.git
$ helm install keda . --values values.yaml --namespace a-m --set metricsServer.dnsPolicy=ClusterFirst,metricsServer.useHostNetwork=true
```
2. Port 9666 is now exposed by default
3. Create scaled object to scale on Kafka
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-consumer-keda-scaled-object
  namespace: a-m
spec:
  scaleTargetRef:
    name: kafka-consumer
  pollingInterval:  10
  cooldownPeriod:   120
  minReplicaCount:  1
  maxReplicaCount:  100
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka-zookeep:9092
      consumerGroup: my-consumer-group
      topic: mytopic1
      lagThreshold: '1'
      offsetResetPolicy: latest
```
4. Check logs again, still the same connection error

### Logs from KEDA operator

Operator from master:
```
2023/11/14 17:17:31 maxprocs: Updating GOMAXPROCS=1: determined from CPU quota
2023-11-14T17:17:31Z	INFO	setup	Starting manager
2023-11-14T17:17:31Z	INFO	setup	KEDA Version: 2.12.0
2023-11-14T17:17:31Z	INFO	setup	Git Commit: 9527a7f1f2797aa5662b2b45b1d26acf22a0cd09
2023-11-14T17:17:31Z	INFO	setup	Go Version: go1.20.8
2023-11-14T17:17:31Z	INFO	setup	Go OS/Arch: linux/amd64
2023-11-14T17:17:31Z	INFO	setup	Running on Kubernetes 1.27+	{"version": "v1.27.7-eks-4f4795d"}
2023-11-14T17:17:31Z	INFO	controller-runtime.metrics	Starting metrics server
2023-11-14T17:17:31Z	INFO	controller-runtime.metrics	Serving metrics server	{"bindAddress": ":8080", "secure": false}
2023-11-14T17:17:31Z	INFO	starting server	{"kind": "health probe", "addr": "[::]:8081"}
I1114 17:17:31.562903       1 leaderelection.go:250] attempting to acquire leader lease a-m/operator.keda.sh...
I1114 17:17:49.215879       1 leaderelection.go:260] successfully acquired lease a-m/operator.keda.sh
2023-11-14T17:17:49Z	INFO	Starting EventSource	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "source": "kind source: *v1alpha1.ScaledObject"}
2023-11-14T17:17:49Z	INFO	Starting EventSource	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "source": "kind source: *v2.HorizontalPodAutoscaler"}
2023-11-14T17:17:49Z	INFO	Starting Controller	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject"}
2023-11-14T17:17:49Z	INFO	Starting EventSource	{"controller": "triggerauthentication", "controllerGroup": "keda.sh", "controllerKind": "TriggerAuthentication", "source": "kind source: *v1alpha1.TriggerAuthentication"}
2023-11-14T17:17:49Z	INFO	Starting Controller	{"controller": "triggerauthentication", "controllerGroup": "keda.sh", "controllerKind": "TriggerAuthentication"}
2023-11-14T17:17:49Z	INFO	Starting EventSource	{"controller": "scaledjob", "controllerGroup": "keda.sh", "controllerKind": "ScaledJob", "source": "kind source: *v1alpha1.ScaledJob"}
2023-11-14T17:17:49Z	INFO	Starting Controller	{"controller": "scaledjob", "controllerGroup": "keda.sh", "controllerKind": "ScaledJob"}
2023-11-14T17:17:49Z	INFO	Starting EventSource	{"controller": "clustertriggerauthentication", "controllerGroup": "keda.sh", "controllerKind": "ClusterTriggerAuthentication", "source": "kind source: *v1alpha1.ClusterTriggerAuthentication"}
2023-11-14T17:17:49Z	INFO	Starting Controller	{"controller": "clustertriggerauthentication", "controllerGroup": "keda.sh", "controllerKind": "ClusterTriggerAuthentication"}
2023-11-14T17:17:49Z	INFO	Starting EventSource	{"controller": "cert-rotator", "source": "kind source: *v1.Secret"}
2023-11-14T17:17:49Z	INFO	Starting EventSource	{"controller": "cert-rotator", "source": "kind source: *unstructured.Unstructured"}
2023-11-14T17:17:49Z	INFO	Starting EventSource	{"controller": "cert-rotator", "source": "kind source: *unstructured.Unstructured"}
2023-11-14T17:17:49Z	INFO	Starting Controller	{"controller": "cert-rotator"}
2023-11-14T17:17:49Z	INFO	cert-rotation	starting cert rotator controller
2023-11-14T17:17:49Z	INFO	cert-rotation	no cert refresh needed
2023-11-14T17:17:49Z	INFO	cert-rotation	certs are ready in /certs
2023-11-14T17:17:49Z	INFO	Starting workers	{"controller": "triggerauthentication", "controllerGroup": "keda.sh", "controllerKind": "TriggerAuthentication", "worker count": 1}
2023-11-14T17:17:49Z	INFO	Starting workers	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "worker count": 5}
2023-11-14T17:17:49Z	INFO	Starting workers	{"controller": "scaledjob", "controllerGroup": "keda.sh", "controllerKind": "ScaledJob", "worker count": 1}
2023-11-14T17:17:49Z	INFO	Starting workers	{"controller": "clustertriggerauthentication", "controllerGroup": "keda.sh", "controllerKind": "ClusterTriggerAuthentication", "worker count": 1}
2023-11-14T17:17:49Z	INFO	Starting workers	{"controller": "cert-rotator", "worker count": 1}
2023-11-14T17:17:49Z	INFO	cert-rotation	no cert refresh needed
2023-11-14T17:17:49Z	INFO	cert-rotation	Ensuring CA cert	{"name": "keda-admission", "gvk": "admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration", "name": "keda-admission", "gvk": "admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration"}
2023-11-14T17:17:49Z	INFO	cert-rotation	Ensuring CA cert	{"name": "v1beta1.external.metrics.k8s.io", "gvk": "apiregistration.k8s.io/v1, Kind=APIService", "name": "v1beta1.external.metrics.k8s.io", "gvk": "apiregistration.k8s.io/v1, Kind=APIService"}
2023-11-14T17:17:49Z	INFO	cert-rotation	no cert refresh needed
2023-11-14T17:17:49Z	INFO	cert-rotation	Ensuring CA cert	{"name": "keda-admission", "gvk": "admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration", "name": "keda-admission", "gvk": "admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration"}
2023-11-14T17:17:49Z	INFO	cert-rotation	Ensuring CA cert	{"name": "v1beta1.external.metrics.k8s.io", "gvk": "apiregistration.k8s.io/v1, Kind=APIService", "name": "v1beta1.external.metrics.k8s.io", "gvk": "apiregistration.k8s.io/v1, Kind=APIService"}
2023-11-14T17:17:50Z	INFO	cert-rotation	CA certs are injected to webhooks
2023-11-14T17:17:50Z	INFO	grpc_server	Starting Metrics Service gRPC Server	{"address": ":9666"}
2023-11-14T17:20:33Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"kafka-consumer-keda-scaled-object","namespace":"a-m"}, "namespace": "a-m", "name": "kafka-consumer-keda-scaled-object", "reconcileID": "41aa5165-7bef-436b-8c27-6166d0b87220"}
2023-11-14T17:20:33Z	INFO	Adding Finalizer for the ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"kafka-consumer-keda-scaled-object","namespace":"a-m"}, "namespace": "a-m", "name": "kafka-consumer-keda-scaled-object", "reconcileID": "41aa5165-7bef-436b-8c27-6166d0b87220"}
2023-11-14T17:20:33Z	INFO	Detected resource targeted for scaling	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"kafka-consumer-keda-scaled-object","namespace":"a-m"}, "namespace": "a-m", "name": "kafka-consumer-keda-scaled-object", "reconcileID": "41aa5165-7bef-436b-8c27-6166d0b87220", "resource": "apps/v1.Deployment", "name": "kafka-consumer"}
2023-11-14T17:20:33Z	INFO	Creating a new HPA	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"kafka-consumer-keda-scaled-object","namespace":"a-m"}, "namespace": "a-m", "name": "kafka-consumer-keda-scaled-object", "reconcileID": "41aa5165-7bef-436b-8c27-6166d0b87220", "HPA.Namespace": "a-m", "HPA.Name": "keda-hpa-kafka-consumer-keda-scaled-object"}
2023-11-14T17:20:33Z	INFO	Initializing Scaling logic according to ScaledObject Specification	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"kafka-consumer-keda-scaled-object","namespace":"a-m"}, "namespace": "a-m", "name": "kafka-consumer-keda-scaled-object", "reconcileID": "41aa5165-7bef-436b-8c27-6166d0b87220"}
2023-11-14T17:20:33Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"kafka-consumer-keda-scaled-object","namespace":"a-m"}, "namespace": "a-m", "name": "kafka-consumer-keda-scaled-object", "reconcileID": "f81f1b43-6a28-408d-8cba-969667dbe48a"}
2023-11-14T17:21:48Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"kafka-consumer-keda-scaled-object","namespace":"a-m"}, "namespace": "a-m", "name": "kafka-consumer-keda-scaled-object", "reconcileID": "6fc7d5da-705d-4cd9-b9ef-2b7adacbed7a"}
2023-11-15T02:47:55Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"kafka-consumer-keda-scaled-object","namespace":"a-m"}, "namespace": "a-m", "name": "kafka-consumer-keda-scaled-object", "reconcileID": "2efe6245-c626-49f8-915f-32ad04f68abb"}
2023-11-15T02:48:55Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"kafka-consumer-keda-scaled-object","namespace":"a-m"}, "namespace": "a-m", "name": "kafka-consumer-keda-scaled-object", "reconcileID": "22ea7c8b-fb1d-4dd4-8b8d-95530b492c48"}
2023-11-15T04:50:55Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"kafka-consumer-keda-scaled-object","namespace":"a-m"}, "namespace": "a-m", "name": "kafka-consumer-keda-scaled-object", "reconcileID": "b2bf6a34-98e0-4d8e-bb24-dedc982392d7"}
2023-11-15T04:51:55Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"kafka-consumer-keda-scaled-object","namespace":"a-m"}, "namespace": "a-m", "name": "kafka-consumer-keda-scaled-object", "reconcileID": "75fa7959-2bc0-43b1-9648-eb95acf9fb66"}
2023-11-15T05:17:49Z	INFO	cert-rotation	no cert refresh needed
2023-11-15T06:00:56Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"kafka-consumer-keda-scaled-object","namespace":"a-m"}, "namespace": "a-m", "name": "kafka-consumer-keda-scaled-object", "reconcileID": "054a7710-5ba7-4225-9ea3-e1c75769cc40"}
2023-11-15T06:01:56Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"kafka-consumer-keda-scaled-object","namespace":"a-m"}, "namespace": "a-m", "name": "kafka-consumer-keda-scaled-object", "reconcileID": "ccea4eea-23fe-4da3-b39c-65c135a933b7"}
```

Logs from metrics-server - are all stack traces

### KEDA Version

2.12.0

### Kubernetes Version

1.27

### Platform

Amazon Web Services

### Scaler Details

Kafka

### Anything else?

EKS version `v1.27.7-eks-4f4795d`

**Comment by JorTurFer** [comment]
Hello,
Is there any reason for using `useHostNetwork=true`?

**Comment by JorTurFer** [comment]
Check the second point because I think that it's your case with EKS: 
![image](https://github.com/kedacore/keda/assets/36899226/fab7f62a-dc77-415b-831a-e6e6bca41c75)
and a bit below in that section
![image](https://github.com/kedacore/keda/assets/36899226/1fffc93c-8d98-4dc9-9d66-3ca8a2a47dd3)
