### ISSUE TITLE
Hit an unsupported type invalid type for invalid type

### ISSUE THREAD

**Issue by ppatierno** [kedacore/keda#599]
While trying to build KEDA, I am facing this error just after running `make build`.

```
GO111MODULE=on CGO_ENABLED=0 GOOS=linux GOARCH=amd64 operator-sdk generate k8s
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [keda:[v1alpha1], ] 
F0202 12:41:29.628587   37511 deepcopy.go:885] Hit an unsupported type invalid type for invalid type, from ./pkg/apis/keda/v1alpha1.ScaledObject
goroutine 1 [running]:
k8s.io/klog.stacks(0xc000558a00, 0xc0003c83c0, 0x91, 0xe1)
        /home/joe/go/pkg/mod/k8s.io/klog@v0.3.3/klog.go:855 +0xb8
k8s.io/klog.(*loggingT).output(0x335c940, 0xc000000003, 0xc0001715e0, 0x3146640, 0xb, 0x375, 0x0)
        /home/joe/go/pkg/mod/k8s.io/klog@v0.3.3/klog.go:806 +0x351
k8s.io/klog.(*loggingT).printf(0x335c940, 0x3, 0x1ee9b04, 0x2a, 0xc000788ed8, 0x3, 0x3)
        /home/joe/go/pkg/mod/k8s.io/klog@v0.3.3/klog.go:705 +0x14b
k8s.io/klog.Fatalf(...)
        /home/joe/go/pkg/mod/k8s.io/klog@v0.3.3/klog.go:1256
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).doStruct(0xc000563000, 0xc000114a50, 0xc000432370)
        /home/joe/go/pkg/mod/k8s.io/gengo@v0.0.0-20191010091904-7fa3014cb28f/examples/deepcopy-gen/generators/deepcopy.go:885 +0x7bd
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).generateFor(0xc000563000, 0xc000114a50, 0xc000432370)
        /home/joe/go/pkg/mod/k8s.io/gengo@v0.0.0-20191010091904-7fa3014cb28f/examples/deepcopy-gen/generators/deepcopy.go:695 +0xc5
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).GenerateType(0xc000563000, 0xc000171500, 0xc000114a50, 0x21b7320, 0xc00000d8a0, 0x0, 0x0)
        /home/joe/go/pkg/mod/k8s.io/gengo@v0.0.0-20191010091904-7fa3014cb28f/examples/deepcopy-gen/generators/deepcopy.go:608 +0xe98
k8s.io/gengo/generator.(*Context).executeBody(0xc000171500, 0x21b42a0, 0xc0004540c0, 0x222f9c0, 0xc000563000, 0x60, 0xc000789288)
        /home/joe/go/pkg/mod/k8s.io/gengo@v0.0.0-20191010091904-7fa3014cb28f/generator/execute.go:306 +0x11c
k8s.io/gengo/generator.(*Context).ExecutePackage(0xc000171340, 0x0, 0x0, 0x2216ba0, 0xc0007a2870, 0x0, 0x0)
        /home/joe/go/pkg/mod/k8s.io/gengo@v0.0.0-20191010091904-7fa3014cb28f/generator/execute.go:267 +0xb25
k8s.io/gengo/generator.(*Context).ExecutePackages(0xc000171340, 0x0, 0x0, 0xc00031da90, 0x1, 0x1, 0x0, 0x30)
        /home/joe/go/pkg/mod/k8s.io/gengo@v0.0.0-20191010091904-7fa3014cb28f/generator/execute.go:51 +0xbf
k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc0006f57c0, 0xc0007897b0, 0x1e886d7, 0x6, 0x1f94440, 0xc0004f9600, 0x18)
        /home/joe/go/pkg/mod/k8s.io/gengo@v0.0.0-20191010091904-7fa3014cb28f/args/args.go:207 +0x1eb
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.deepcopyGen(0xc00041d080, 0xe, 0xc0003e67b0, 0x1, 0x1, 0x0, 0xc0000ec750)
        /home/joe/projects/work/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/k8s.go:95 +0x4d9
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.K8sCodegen.func1(0xc00041d080, 0xe, 0x0, 0x0)
        /home/joe/projects/work/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/k8s.go:54 +0x50
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.generateWithHeaderFile(0xc000789c00, 0x0, 0x0)
        /home/joe/projects/work/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/genutil.go:46 +0x175
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.K8sCodegen(0xc0002d0f00, 0x0)
        /home/joe/projects/work/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/k8s.go:55 +0x48d
github.com/operator-framework/operator-sdk/cmd/operator-sdk/generate.k8sFunc(0xc0002d0f00, 0x33841d8, 0x0, 0x0, 0x0, 0x0)
        /home/joe/projects/work/operator-framework/operator-sdk/cmd/operator-sdk/generate/k8s.go:56 +0x64
github.com/spf13/cobra.(*Command).execute(0xc0002d0f00, 0x33841d8, 0x0, 0x0, 0xc0002d0f00, 0x33841d8)
        /home/joe/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000388f00, 0x21b8d40, 0xc000617800, 0x0)
        /home/joe/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/joe/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /home/joe/projects/work/operator-framework/operator-sdk/cmd/operator-sdk/main.go:84 +0x584
make: *** [Makefile:76: generate-api] Error 255
```

I noticed that it can be fixed exporting the `GOROOT` env var in bash (while it's ok by running `go env GOROOT`). Is it just me having this problem? Otherwise I think it should be mentioned in the building guide.

I am on Fedora 31, go version 1.13.6

**Comment by zroubalik** [comment]
#600 is merged
