### ISSUE TITLE
RHEL 7 make build: Hit an unsupported type invalid type for invalid type

### ISSUE THREAD

**Issue by inuyasha82** [kedacore/keda#693]
I'm trying to build keda on RHEL 7

The build is failing with the following error: 

```
GO111MODULE=on  CGO_ENABLED=0 GOOS=linux GOARCH=amd64 operator-sdk generate k8s
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [keda:[v1alpha1], ] 
F0320 09:43:09.486082   15796 deepcopy.go:885] Hit an unsupported type invalid type for invalid type, from ./pkg/apis/keda/v1alpha1.ScaledObject
goroutine 1 [running]:
k8s.io/klog.stacks(0xc00001e200, 0xc00015c4b0, 0x91, 0xe1)
	/home/joe/go/pkg/mod/k8s.io/klog@v0.3.3/klog.go:855 +0xb8
k8s.io/klog.(*loggingT).output(0x335c940, 0xc000000003, 0xc000442310, 0x3146640, 0xb, 0x375, 0x0)
	/home/joe/go/pkg/mod/k8s.io/klog@v0.3.3/klog.go:806 +0x351
k8s.io/klog.(*loggingT).printf(0x335c940, 0x3, 0x1ee9b04, 0x2a, 0xc0007d2ed8, 0x3, 0x3)
	/home/joe/go/pkg/mod/k8s.io/klog@v0.3.3/klog.go:705 +0x14b
k8s.io/klog.Fatalf(...)
	/home/joe/go/pkg/mod/k8s.io/klog@v0.3.3/klog.go:1256
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).doStruct(0xc000446500, 0xc0000dbad0, 0xc0007fe370)
	/home/joe/go/pkg/mod/k8s.io/gengo@v0.0.0-20191010091904-7fa3014cb28f/examples/deepcopy-gen/generators/deepcopy.go:885 +0x7bd
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).generateFor(0xc000446500, 0xc0000dbad0, 0xc0007fe370)
	/home/joe/go/pkg/mod/k8s.io/gengo@v0.0.0-20191010091904-7fa3014cb28f/examples/deepcopy-gen/generators/deepcopy.go:695 +0xc5
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).GenerateType(0xc000446500, 0xc0004422a0, 0xc0000dbad0, 0x21b7320, 0xc000322e20, 0x0, 0x0)
	/home/joe/go/pkg/mod/k8s.io/gengo@v0.0.0-20191010091904-7fa3014cb28f/examples/deepcopy-gen/generators/deepcopy.go:608 +0xe98
k8s.io/gengo/generator.(*Context).executeBody(0xc0004422a0, 0x21b42a0, 0xc0005601b0, 0x222f9c0, 0xc000446500, 0x60, 0xc0007d3288)
	/home/joe/go/pkg/mod/k8s.io/gengo@v0.0.0-20191010091904-7fa3014cb28f/generator/execute.go:306 +0x11c
k8s.io/gengo/generator.(*Context).ExecutePackage(0xc00014c1c0, 0x0, 0x0, 0x2216ba0, 0xc0003d9170, 0x0, 0x0)
	/home/joe/go/pkg/mod/k8s.io/gengo@v0.0.0-20191010091904-7fa3014cb28f/generator/execute.go:267 +0xb25
k8s.io/gengo/generator.(*Context).ExecutePackages(0xc00014c1c0, 0x0, 0x0, 0xc00059e1d0, 0x1, 0x1, 0x0, 0x30)
	/home/joe/go/pkg/mod/k8s.io/gengo@v0.0.0-20191010091904-7fa3014cb28f/generator/execute.go:51 +0xbf
k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc00041ce60, 0xc0007d37b0, 0x1e886d7, 0x6, 0x1f94440, 0xc0005d07e0, 0x18)
	/home/joe/go/pkg/mod/k8s.io/gengo@v0.0.0-20191010091904-7fa3014cb28f/args/args.go:207 +0x1eb
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.deepcopyGen(0xc0002ef230, 0xe, 0xc000456100, 0x1, 0x1, 0x0, 0xc0004ba248)
	/home/joe/projects/work/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/k8s.go:95 +0x4d9
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.K8sCodegen.func1(0xc0002ef230, 0xe, 0x0, 0x0)
	/home/joe/projects/work/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/k8s.go:54 +0x50
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.generateWithHeaderFile(0xc0006d1c00, 0x0, 0x0)
	/home/joe/projects/work/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/genutil.go:46 +0x175
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.K8sCodegen(0xc00035bb80, 0x0)
	/home/joe/projects/work/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/k8s.go:55 +0x48d
github.com/operator-framework/operator-sdk/cmd/operator-sdk/generate.k8sFunc(0xc00035bb80, 0x33841d8, 0x0, 0x0, 0x0, 0x0)
	/home/joe/projects/work/operator-framework/operator-sdk/cmd/operator-sdk/generate/k8s.go:56 +0x64
github.com/spf13/cobra.(*Command).execute(0xc00035bb80, 0x33841d8, 0x0, 0x0, 0xc00035bb80, 0x33841d8)
	/home/joe/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000134a00, 0x21b8d40, 0xc0003d3400, 0x0)
	/home/joe/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/joe/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/home/joe/projects/work/operator-framework/operator-sdk/cmd/operator-sdk/main.go:84 +0x584
make: *** [generate-api] Error 255
```
I'm already aware of the issue number #599  and tried to set the GOROOT variable as described, but it doesn't work. 

There is only one tiny difference between GOROOT variable set and unset, how long i have to wait before getting the error, if unset it is immediate, instead if set it appears after 40 seconds more or less. 

The GOROOT variable is set using the following command: 

`export GOROOT=$(go env GOROOT)`

and is set as the path: /usr/lib/golang

The version of go i'm using is 1.13.3
Operator sdk version i'm using is 0.12.0

## Expected Behavior
Keda should build fine

## Actual Behavior

The error above

## Steps to Reproduce the Problem

  1. A rhel 7 machine is needed with go
  2. Just run make build (with or without the GOROOT variable set) 
  3.

## Specifications

  - **KEDA Version:** *master*
  - **Platform & Version:** *RHEL7*
  - **Kubernetes Version:** *1.17.0*
  - **Scaler(s):** *n/a*

**Comment by zroubalik** [comment]
@inuyasha82 are you able to build another operator-sdk based operator on that machine?

**Comment by inuyasha82** [comment]
haven't tried it, an example of operator i can build?

**Comment by inuyasha82** [comment]
@zroubalik 

So i spent more time on trying to figure out a solution, and i managed to build it. 

So basically, not sure if this is an issue with the operator-sdk documention, or anyway a specific issue of RHEL, but i had to setup the GOPROXY environment variable manually. 

The problem looks to be that on RHEL 7 the GOPROXY env variable is set by default to "direct", while i checked on macOS and on linux debian is set to: https://proxy.golang.org,direct

So i think the problem is in the configuration of Go in RHEL. 

Of course the GOROOT variable is still needed, but not enough to build it on Red Hat

So probably the solution for anyone that face this issue is to export the following env variables: 

```
export GOPROXY=https://proxy.golang.org,direct
export GOROOT=$(go env GOROOT)
```

Interesting thing is that the GOPROXY thing is a note in the installation guide of operator-sdk, but apparently it is referred only if you want to build operator-sdk from source.

**Comment by zroubalik** [comment]
@inuyasha82 interesting, thanks for the update! I'm glad it is working now.
